# exampleSite/config.yaml
baseURL: https://jaquiel.github.io/ # Replace with your domain
languageCode: en-us
# themesDir: ../.. # Only needed for running the example site
title: Jaquiel Paim
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
params:
  abbrDateFmt: "Jan 2"
  author: "Jaquiel Paim"
  brandIconFile: "images/brandIcon.svg"
  dateFmt: "2006-01-02"
#  customStylesheets: # Use to override theme styles, like logo size
#    - "css/custom.css"
  social:
    - name: GitHub
      url: https://github.com/jaquiel
    - name: Linkedin
      url: https://www.linkedin.com/in/jaquielpaim/?locale=en_US
    - name: Twitter
      url: https://twitter.com/JaquielPaim
  subtitle: "Just a software engineer talking about technology."
